version: '3.7'
services:
  apache-php-5.6:
    build:
      context: ${CONTEXTO_APLICACAO_APACHE}
      dockerfile: ${DIRETORIO_DOCKERFILE_APACHE}
    # image: ${NOME_IMAGEM}:${TAG_DA_IMAGEM}
    container_name: ${NOME_CONTAINER_APACHE}
    restart: always
    volumes:
      - ${DIRETORIO_VOLUME_APACHE}:/var/www/html
    ports:
      - ${PORTA_CONTAINER_APACHE}:80

  # mysql-5.6:
  #   container_name: ${NOME_CONTAINER_MYSQL}
  #   image: ${IMAGEM_CONTAINER_MYSQL}
  #   restart: always
  #   volumes:
  #     - ${DIRETORIO_VOLUME_MYSQL}:/var/lib/mysql
  #   environment:
  #     TZ: ${TIMEZONE_MYSQL}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_APP_ROOT_PASSWORD}
  #     MYSQL_ROOT_HOST: ${MYSQL_HOST}
  #   ports:
  #     - ${PORTA_CONTAINER_MYSQL}:3306

  # mysql-8:
  #   container_name: mysql-8
  #   image: mysql:8.0-debian
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   volumes:
  #     - $PWD/bancos/banco-mysql-8:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_ROOT_HOST=%
  #   ports:
  #     - 3308:3306
